"""create deviations table

Revision ID: e72a7777bf0d
Revises: 
Create Date: 2026-09-26 20:58:59.337988
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e72a7777bf0d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deviation_number', sa.String(length=32), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('date_of_occurrence', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assessment_level'), nullable=True),
    sa.Column('impact_reason', sa.Text(), nullable=True),
    sa.Column('severity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assessment_level'), nullable=True),
    sa.Column('severity_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'SUBMITTED', 'CLOSED', name='deviation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deviations_deviation_number'), 'deviations', ['deviation_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deviations_deviation_number'), table_name='deviations')
    op.drop_table('deviations')
    # ### end Alembic commands ###
